package com.thaumicrecipeaspectpatcher.trap.config;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.JsonToNBT;
import net.minecraft.nbt.NBTException;
import net.minecraft.nbt.NBTTagCompound;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectEventProxy;
import thaumcraft.api.aspects.AspectList;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.*;

/**
 * On-disk aspect cache written by the client (via JEI) and loaded by both
 * client and server.
 *
 * File location: {@code config/trap_cache.json}
 *
 * Validity is determined by comparing the SHA-1 hash of {@code trap.cfg}
 * stored in the cache against the current file.  When the config changes the
 * client invalidates the cache and recomputes on the next login.
 *
 * The server only ever reads this file; it never writes it.  On a dedicated
 * server the cache must be pre-generated by a client and distributed together
 * with the config file.
 */
public class TRAPCache {

    private static final Logger LOGGER = LogManager.getLogger("TRAP");
    public static final String CACHE_FILENAME = "trap_cache.json";
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    /**
     * Incremented whenever the cache format or parsing logic changes in a way
     * that makes old cached data invalid.
     */
    public static final int CURRENT_FORMAT_VERSION = 2;

    /** Format version stored when this cache was written. */
    public int formatVersion;

    /** SHA-1 hex of {@code trap.cfg} at the time this cache was last built. */
    public String configHash;

    /** All computed item → aspects assignments. */
    public List<Entry> entries = new ArrayList<>();

    // -------------------------------------------------------------------------

    /** One item → aspects mapping entry persisted in JSON. */
    public static class Entry {
        /** Item registry name, e.g. {@code minecraft:cobblestone}. */
        public String registryName;
        /** Item metadata / damage value. */
        public int meta;
        /** Serialised SNBT string, or {@code null} if the stack has no NBT. */
        public String nbt;
        /** Aspect tag (e.g. {@code "terra"}) → amount. */
        public Map<String, Integer> aspects = new LinkedHashMap<>();

        /** Build an Entry from a live ItemStack and the computed AspectList. */
        public static Entry of(ItemStack stack, AspectList aspectList) {
            Entry e = new Entry();
            e.registryName = stack.getItem().getRegistryName().toString();
            e.meta = stack.getMetadata();
            e.nbt = stack.hasTagCompound() ? stack.getTagCompound().toString() : null;
            for (Aspect aspect : aspectList.getAspects()) {
                e.aspects.put(aspect.getTag(), aspectList.getAmount(aspect));
            }
            return e;
        }

        /**
         * Reconstruct the ItemStack from this entry's registry name, meta, and
         * optional NBT.  Returns {@code null} if the item is unknown in this
         * environment (e.g. the mod that adds the item is not installed
         * server-side).
         */
        public ItemStack toItemStack() {
            Item item = Item.getByNameOrId(registryName);
            if (item == null) return null;
            ItemStack stack = new ItemStack(item, 1, meta);
            if (nbt != null && !nbt.isEmpty()) {
                try {
                    NBTTagCompound tag = JsonToNBT.getTagFromJson(nbt);
                    stack.setTagCompound(tag);
                } catch (NBTException ex) {
                    LOGGER.warn("TRAP cache: cannot parse NBT for '{}': {}", registryName, ex.getMessage());
                }
            }
            return stack;
        }

        /** Reconstruct the AspectList.  Missing aspects are silently skipped. */
        public AspectList toAspectList() {
            AspectList list = new AspectList();
            for (Map.Entry<String, Integer> e : aspects.entrySet()) {
                Aspect aspect = Aspect.aspects.get(e.getKey());
                if (aspect != null) {
                    list.add(aspect, e.getValue());
                }
            }
            return list;
        }
    }

    // -------------------------------------------------------------------------

    /**
     * Apply all cache entries to Thaumcraft's objectTags via
     * {@link AspectEventProxy#registerComplexObjectTag}.
     *
     * Safe to call on both client and server threads.  Unknown items (registry
     * name not present in this environment) are skipped with a debug log.
     *
     * @return number of entries successfully applied.
     */
    public int apply() {
        AspectEventProxy proxy = new AspectEventProxy();
        int count = 0;
        for (Entry entry : entries) {
            ItemStack stack = entry.toItemStack();
            if (stack == null || stack.isEmpty()) {
                LOGGER.debug("TRAP cache: skipping unknown item '{}'", entry.registryName);
                continue;
            }
            AspectList aspectList = entry.toAspectList();
            if (aspectList.size() == 0) continue;
            proxy.registerComplexObjectTag(stack, aspectList);
            count++;
        }
        return count;
    }

    // -------------------------------------------------------------------------

    /**
     * Load the cache from disk.
     * Returns {@code null} if the file does not exist or cannot be parsed.
     */
    public static TRAPCache load(File configDir) {
        File cacheFile = new File(configDir, CACHE_FILENAME);
        if (!cacheFile.exists()) return null;
        try (Reader reader = new InputStreamReader(
                new FileInputStream(cacheFile), StandardCharsets.UTF_8)) {
            TRAPCache cache = GSON.fromJson(reader, TRAPCache.class);
            if (cache == null || cache.entries == null) return null;
            return cache;
        } catch (Exception e) {
            LOGGER.warn("TRAP: failed to read cache '{}': {}", cacheFile.getAbsolutePath(), e.getMessage());
            return null;
        }
    }

    /** Write this cache to {@code config/trap_cache.json}. */
    public void save(File configDir) {
        File cacheFile = new File(configDir, CACHE_FILENAME);
        try (Writer writer = new OutputStreamWriter(
                new FileOutputStream(cacheFile), StandardCharsets.UTF_8)) {
            GSON.toJson(this, writer);
            LOGGER.info("TRAP: saved {} aspect entries to '{}'.", entries.size(), CACHE_FILENAME);
        } catch (IOException e) {
            LOGGER.error("TRAP: failed to write cache '{}': {}", cacheFile.getAbsolutePath(), e.getMessage());
        }
    }

    /**
     * Returns {@code true} if the config hash stored inside this cache matches
     * the current content of {@code trap.cfg}, AND the format version matches.
     */
    public boolean isValid(File configDir) {
        if (formatVersion != CURRENT_FORMAT_VERSION) return false;
        String current = hashConfigFile(configDir);
        return current != null && current.equals(configHash);
    }

    /**
     * Compute the SHA-1 hex digest of {@code config/trap.cfg}.
     * Returns {@code null} on any error.
     */
    public static String hashConfigFile(File configDir) {
        File cfg = new File(configDir, "trap.cfg");
        if (!cfg.exists()) return null;
        try (InputStream is = new FileInputStream(cfg)) {
            MessageDigest digest = MessageDigest.getInstance("SHA-1");
            byte[] buf = new byte[8192];
            int n;
            while ((n = is.read(buf)) != -1) {
                digest.update(buf, 0, n);
            }
            byte[] hash = digest.digest();
            StringBuilder sb = new StringBuilder(40);
            for (byte b : hash) sb.append(String.format("%02x", b));
            return sb.toString();
        } catch (IOException | NoSuchAlgorithmException e) {
            LOGGER.warn("TRAP: cannot hash config file: {}", e.getMessage());
            return null;
        }
    }
}
