package com.thaumicrecipeaspectpatcher.trap;

import com.thaumicrecipeaspectpatcher.trap.config.TRAPCache;
import com.thaumicrecipeaspectpatcher.trap.config.TRAPConfig;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Main mod class for ThaumicRecipeAspectPatcher.
 *
 * Lifecycle:
 *   preInit  — loads config/trap.cfg into TRAPConfig.INSTANCE (both sides).
 *   serverStarting — loads config/trap_cache.json and applies the cached
 *                    aspect overrides to Thaumcraft's objectTags.  This covers
 *                    both dedicated servers (which never run JEI) and
 *                    integrated servers (complementing the client-side JEI
 *                    plugin that already applied the same data).
 *
 * JEI note: we intentionally do NOT reference TRAPJeiPlugin here.  That class
 * imports mezz.jei.api.* and would cause ClassNotFoundException on any
 * environment where JEI is absent.  JEI discovers the plugin via @JEIPlugin.
 */
@Mod(
    modid    = Tags.MOD_ID,
    name     = Tags.MOD_NAME,
    version  = Tags.VERSION,
    dependencies = "required-after:thaumcraft;after:jei"
)
public class ThaumicRecipeAspectPatcher {

    public static final Logger LOGGER = LogManager.getLogger(Tags.MOD_NAME);

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        TRAPConfig cfg = new TRAPConfig();
        cfg.load(event.getModConfigurationDirectory());
        TRAPConfig.INSTANCE = cfg;
        LOGGER.info("{} pre-init complete. Config loaded.", Tags.MOD_NAME);
    }

    /**
     * Called on both integrated-server and dedicated-server startup.
     *
     * Loads {@code config/trap_cache.json} (written by the client JEI plugin)
     * and applies the stored aspect overrides to the server's objectTags via
     * {@code AspectEventProxy.registerComplexObjectTag}.
     *
     * On a dedicated server the cache file must be pre-generated by a client
     * and placed in the server's {@code config/} folder.  If the file is absent
     * a warning is logged but the server continues to start normally.
     */
    @Mod.EventHandler
    public void serverStarting(FMLServerStartingEvent event) {
        TRAPConfig config = TRAPConfig.INSTANCE;
        if (config == null) {
            LOGGER.warn("TRAP: TRAPConfig.INSTANCE is null during serverStarting - skipping cache load.");
            return;
        }

        TRAPCache cache = TRAPCache.load(config.getConfigDir());
        if (cache == null) {
            LOGGER.warn("TRAP: No aspect cache found ({}/{}). "
                    + "Start a client first to generate it, then copy it to the server.",
                    config.getConfigDir().getName(), TRAPCache.CACHE_FILENAME);
            return;
        }

        int applied = cache.apply();
        LOGGER.info("TRAP: Server applied {} aspect override(s) from cache.", applied);
    }
}
